/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libros2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author PC
 */
public class CrearUsu extends javax.swing.JFrame {
    DefaultTableModel dtm;
    
   
        
    public CrearUsu() {
        initComponents();
        dtm = (DefaultTableModel) this.jTblLibros.getModel();
        
        
    }

    private void table(){
        
        String registros[] = new String[4];
        
        registros[0] = jTXNOMBRE.getText();
        registros[1] = jTXCONTRA.getText();
        registros[2] = jTXAPELLIDO.getText();
        registros[3] = jTXROL.getText();
        
 
        dtm.addRow(registros);
 
        jTXNOMBRE.setText("");
        jTXCONTRA.setText("");
        jTXAPELLIDO.setText("");
        jTXROL.setText("");
           }
          private void guardarArchivo(){
        try {
            FileWriter salvarArchivo = new FileWriter("usuario.txt");
           
            
            for (int i=0; i < this.jTblLibros.getRowCount(); i++){
                salvarArchivo.write(dtm.getValueAt(i, 0).toString() + "\n");
                salvarArchivo.write(dtm.getValueAt(i, 1).toString() + "\n");
                salvarArchivo.write(dtm.getValueAt(i, 2).toString() + "\n");
                salvarArchivo.write(dtm.getValueAt(i, 3).toString() + "\n");
                
                
            }
            salvarArchivo.close();
            JOptionPane.showMessageDialog(null, "Datos Almacenados","Gestion de Archivos", 1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erorr" + ex);
        
        }
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLNOMBRE = new javax.swing.JLabel();
        jLAPELLIDO = new javax.swing.JLabel();
        jLCONTRA = new javax.swing.JLabel();
        jLROL = new javax.swing.JLabel();
        jTXROL = new javax.swing.JTextField();
        jTXCONTRA = new javax.swing.JTextField();
        jTXNOMBRE = new javax.swing.JTextField();
        jTXAPELLIDO = new javax.swing.JTextField();
        jBguardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblLibros = new javax.swing.JTable();
        jBttingresarO = new javax.swing.JButton();
        jBregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CREAR USUARIOS");

        jLNOMBRE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLNOMBRE.setText("NOMBRE");

        jLAPELLIDO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLAPELLIDO.setText("APELLIDO");

        jLCONTRA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLCONTRA.setText("CONTRASEÑA");

        jLROL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLROL.setText("ROL");

        jTXROL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTXCONTRA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTXNOMBRE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTXAPELLIDO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jBguardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBguardar.setText("GUARDAR");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jTblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "CONTRASEÑA", "APELLIDO", "ROL", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(jTblLibros);

        jBttingresarO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBttingresarO.setText("INGRESAR USUARIO");
        jBttingresarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttingresarOActionPerformed(evt);
            }
        });

        jBregresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBregresar.setText("REGRESAR");
        jBregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCONTRA)
                        .addGap(97, 97, 97)
                        .addComponent(jTXCONTRA))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAPELLIDO)
                            .addComponent(jLNOMBRE))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTXAPELLIDO)
                            .addComponent(jTXNOMBRE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLROL)
                        .addGap(176, 176, 176)
                        .addComponent(jTXROL)))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jBttingresarO)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBguardar)
                        .addGap(65, 65, 65)
                        .addComponent(jBregresar)
                        .addGap(140, 140, 140))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNOMBRE)
                    .addComponent(jTXNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLAPELLIDO)
                    .addComponent(jTXAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLCONTRA)
                    .addComponent(jTXCONTRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLROL)
                    .addComponent(jTXROL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jBttingresarO)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardar)
                    .addComponent(jBregresar))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        guardarArchivo();
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBttingresarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttingresarOActionPerformed
        table();
    }//GEN-LAST:event_jBttingresarOActionPerformed

    private void jBregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregresarActionPerformed
        menuadmin nF = new menuadmin();
            nF.setVisible(true);
            dispose();        
    }//GEN-LAST:event_jBregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBregresar;
    private javax.swing.JButton jBttingresarO;
    private javax.swing.JLabel jLAPELLIDO;
    private javax.swing.JLabel jLCONTRA;
    private javax.swing.JLabel jLNOMBRE;
    private javax.swing.JLabel jLROL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTXAPELLIDO;
    private javax.swing.JTextField jTXCONTRA;
    private javax.swing.JTextField jTXNOMBRE;
    private javax.swing.JTextField jTXROL;
    private javax.swing.JTable jTblLibros;
    // End of variables declaration//GEN-END:variables
}
