/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libros2;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class modiuser extends javax.swing.JPanel {

    /**
     * Creates new form modiuser
     */
    public modiuser() {
        initComponents();
    }
    private void mostrarArchivo(){
          String id, Nombre, Autor, Editorial, anio;
        
        String au = "C:\\Ventas\\admin\\usuario.txt";
        
        File arcLectura = new File(au);
        try {
           Scanner lecturaArchivo = new Scanner(arcLectura);
           
           while(lecturaArchivo.hasNextLine()){
               id = lecturaArchivo.nextLine();
               Nombre = lecturaArchivo.nextLine();
               Autor = lecturaArchivo.nextLine();
               Editorial = lecturaArchivo.nextLine();
               anio = lecturaArchivo.nextLine();
               
               dtm.addRow(new Object[]{id, Nombre, Autor, Editorial, anio});
           }
        }catch (FileNotFoundException e) {
             JOptionPane.showMessageDialog(null, "Erorr" + e);
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBguardar = new javax.swing.JButton();
        jBregresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblLibros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jBguardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBguardar.setText("GUARDAR");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBregresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBregresar.setText("REGRESAR");
        jBregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregresarActionPerformed(evt);
            }
        });

        jTblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "CONTRASEÑA", "APELLIDO", "ROL", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(jTblLibros);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MODIFICAR USUARIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBregresar)
                        .addComponent(jBguardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jBguardar)
                .addGap(18, 18, 18)
                .addComponent(jBregresar)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregresarActionPerformed
        
    }//GEN-LAST:event_jBregresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBregresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblLibros;
    // End of variables declaration//GEN-END:variables
}
